// <auto-generated />
using System;
using FinalProject_3K1D.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_3K1D.Migrations
{
    [DbContext(typeof(QlrapPhimContext))]
    [Migration("20240911071936_ConstraintModelVeAndFoodsByidsanpham")]
    partial class ConstraintModelVeAndFoodsByidsanpham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_3K1D.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .HasColumnType("int")
                        .HasColumnName("idChucVu");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.DanhGia", b =>
                {
                    b.Property<int>("IdDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhGia"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("IdKhachHang")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdPhim")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiDanhGia")
                        .HasColumnType("bit");

                    b.HasKey("IdDanhGia");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdPhim");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Food", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPham"));

                    b.Property<string>("Apphich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPham");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.GiaHoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("PhanTramHoan")
                        .HasColumnType("float");

                    b.Property<int>("ThoiGianHoan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GiaHoans");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.KhachHang", b =>
                {
                    b.Property<string>("IdKhachHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idKhachHang");

                    b.Property<string>("Cccd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DienTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("PassKh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PassKH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SDT");

                    b.Property<string>("UserKh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserKH");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.KhuyenMai", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("idKhuyenMai");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("money");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdKhuyenMai");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.LichChieu", b =>
                {
                    b.Property<string>("IdLichChieu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idLichChieu");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("money");

                    b.Property<DateTime>("GioChieu")
                        .HasColumnType("datetime");

                    b.Property<string>("IdPhim")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idPhim");

                    b.Property<string>("IdPhongChieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idPhongChieu");

                    b.Property<string>("IdRap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdRapNavigationIdRap")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdLichChieu")
                        .HasName("PK__LichChie__A56F50C2523BC244");

                    b.HasIndex("IdPhim");

                    b.HasIndex("IdPhongChieu");

                    b.HasIndex("IdRapNavigationIdRap");

                    b.ToTable("LichChieu", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.NhanVien", b =>
                {
                    b.Property<string>("IdNhanVien")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idNhanVien");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdChucVu")
                        .HasColumnType("int")
                        .HasColumnName("idChucVu");

                    b.Property<string>("IdRap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idRap");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("PassNv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PassNV");

                    b.Property<string>("Sdt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SDT");

                    b.Property<string>("UserNv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserNV");

                    b.HasKey("IdNhanVien")
                        .HasName("PK_NhanV");

                    b.HasIndex("IdChucVu");

                    b.HasIndex("IdRap");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Phim", b =>
                {
                    b.Property<string>("IdPhim")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idPhim");

                    b.Property<string>("ApPhich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DaoDien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DinhDangPhim")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NamSx")
                        .HasColumnType("int")
                        .HasColumnName("NamSX");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKhoiChieu")
                        .HasColumnType("date");

                    b.Property<string>("QuocGiaSanXuat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ThoiLuong")
                        .HasColumnType("float");

                    b.HasKey("IdPhim")
                        .HasName("PK__Phim__BFC6F6835535CAE4");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.PhongChieu", b =>
                {
                    b.Property<string>("IdPhongChieu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idPhongChieu");

                    b.Property<string>("IdRap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idRap");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPhongChieu")
                        .HasName("PK__PhongChi__A985F624FD920998");

                    b.HasIndex("IdRap");

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Rap", b =>
                {
                    b.Property<string>("IdRap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idRap");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenRap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRap")
                        .HasName("PK_Rap1");

                    b.ToTable("Rap", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.TheLoai", b =>
                {
                    b.Property<string>("IdTheLoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idTheLoai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTheLoai")
                        .HasName("PK__TheLoai__890D7EC86D98E64D");

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Ve", b =>
                {
                    b.Property<int>("IdVe")
                        .HasColumnType("int");

                    b.Property<string>("IdKhachHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idKhachHang");

                    b.Property<string>("IdLichChieu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idLichChieu");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiVe")
                        .HasColumnType("int");

                    b.Property<string>("MaGheNgoi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayMua")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SanPhamNavigationIdSanPham")
                        .HasColumnType("int");

                    b.Property<decimal?>("TienBanVe")
                        .HasColumnType("money");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdVe");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IdVe"), false);

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdLichChieu");

                    b.HasIndex("SanPhamNavigationIdSanPham");

                    b.HasIndex(new[] { "IdVe" }, "IX_Ve");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex(new[] { "IdVe" }, "IX_Ve"));

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("PhanLoaiPhim", b =>
                {
                    b.Property<string>("IdPhim")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idPhim");

                    b.Property<string>("IdTheLoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idTheLoai");

                    b.HasKey("IdPhim", "IdTheLoai");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("PhanLoaiPhim", (string)null);
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.DanhGia", b =>
                {
                    b.HasOne("FinalProject_3K1D.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_3K1D.Models.Phim", "Phim")
                        .WithMany("DanhGias")
                        .HasForeignKey("IdPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.LichChieu", b =>
                {
                    b.HasOne("FinalProject_3K1D.Models.Phim", "IdPhimNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("IdPhim")
                        .HasConstraintName("FK_LichChieu_Phim");

                    b.HasOne("FinalProject_3K1D.Models.PhongChieu", "IdPhongChieuNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("IdPhongChieu")
                        .IsRequired()
                        .HasConstraintName("FK__LichChieu__idPho__4AB81AF0");

                    b.HasOne("FinalProject_3K1D.Models.Rap", "IdRapNavigation")
                        .WithMany()
                        .HasForeignKey("IdRapNavigationIdRap");

                    b.Navigation("IdPhimNavigation");

                    b.Navigation("IdPhongChieuNavigation");

                    b.Navigation("IdRapNavigation");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.NhanVien", b =>
                {
                    b.HasOne("FinalProject_3K1D.Models.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu")
                        .HasConstraintName("FK_NhanVien_ChucVu");

                    b.HasOne("FinalProject_3K1D.Models.Rap", "IdRapNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdRap")
                        .HasConstraintName("FK_NhanVien_Rap");

                    b.Navigation("IdChucVuNavigation");

                    b.Navigation("IdRapNavigation");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.PhongChieu", b =>
                {
                    b.HasOne("FinalProject_3K1D.Models.Rap", "IdRapNavigation")
                        .WithMany("PhongChieus")
                        .HasForeignKey("IdRap")
                        .HasConstraintName("FK_PhongChieu_Rap");

                    b.Navigation("IdRapNavigation");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Ve", b =>
                {
                    b.HasOne("FinalProject_3K1D.Models.KhachHang", "IdKhachHangNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("IdKhachHang")
                        .HasConstraintName("FK_Ve_KhachHang");

                    b.HasOne("FinalProject_3K1D.Models.LichChieu", "IdLichChieuNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("IdLichChieu")
                        .HasConstraintName("FK_Ve_LichChieu");

                    b.HasOne("FinalProject_3K1D.Models.Food", "SanPhamNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("SanPhamNavigationIdSanPham");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdLichChieuNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("PhanLoaiPhim", b =>
                {
                    b.HasOne("FinalProject_3K1D.Models.Phim", null)
                        .WithMany()
                        .HasForeignKey("IdPhim")
                        .IsRequired()
                        .HasConstraintName("FK__PhanLoaiP__idPhi__4CA06362");

                    b.HasOne("FinalProject_3K1D.Models.TheLoai", null)
                        .WithMany()
                        .HasForeignKey("IdTheLoai")
                        .IsRequired()
                        .HasConstraintName("FK__PhanLoaiP__idThe__4D94879B");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Food", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.KhachHang", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.LichChieu", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Phim", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("LichChieus");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.PhongChieu", b =>
                {
                    b.Navigation("LichChieus");
                });

            modelBuilder.Entity("FinalProject_3K1D.Models.Rap", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhongChieus");
                });
#pragma warning restore 612, 618
        }
    }
}
